import React from 'react';
import { FaTimes, FaLightbulb } from 'react-icons/fa';

const HintModal = ({ isOpen, onClose, problem }) => {
    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50 backdrop-blur-sm p-4">
            <div className="bg-white dark:bg-leet-card w-full max-w-md rounded-lg shadow-xl overflow-hidden">
                <div className="flex justify-between items-center p-4 border-b dark:border-leet-border bg-yellow-100 dark:bg-yellow-900">
                    <h3 className="text-lg font-bold text-yellow-800 dark:text-yellow-100 flex items-center gap-2">
                        <FaLightbulb /> Hint: {problem?.title || 'Problem'}
                    </h3>
                    <button onClick={onClose} className="text-yellow-800 dark:text-yellow-100 hover:opacity-80">
                        <FaTimes />
                    </button>
                </div>
                <div className="p-6 text-gray-700 dark:text-gray-300">
                    <p className="mb-4">Here is a gentle nudge to help you solve this:</p>
                    <div className="bg-gray-100 dark:bg-leet-input p-4 rounded-md border-l-4 border-yellow-500 italic">
                        "Consider using a Hash Map to store visited elements for O(1) lookups."
                        <br /><br />
                        (This is a placeholder hint. In the future, this will be generated by AI based on the specific problem.)
                    </div>
                </div>
                <div className="p-4 border-t dark:border-leet-border flex justify-end">
                    <button onClick={onClose} className="bg-gray-200 dark:bg-leet-input hover:bg-gray-300 dark:hover:bg-gray-600 text-gray-800 dark:text-white px-4 py-2 rounded">
                        Got it!
                    </button>
                </div>
            </div>
        </div>
    );
};

export default HintModal;
